### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Galen-xiaogao** [Zhengqbbb/cz-git#64]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
npx: installed 4 in 5.374s
Watching D:\temp\menu-admin and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.git ; is listed in .gitignore
Found & ignored ./.husky ; is listed in .gitignore
Found & ignored ./.idea ; is listed in .gitignore
Found & ignored ./.vscode ; is listed in .gitignore
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./public ; is listed in .gitignore
Found & ignored ./src ; is listed in .gitignore
Found & ignored ./auto-imports.d.ts ; is listed in .gitignore
Found & ignored ./CHANGELOG.md ; is listed in .gitignore
Found & ignored ./commitlint.config.js ; is listed in .gitignore
Found & ignored ./components.d.ts ; is listed in .gitignore
Found & ignored ./index.html ; is listed in .gitignore
Found & ignored ./lint-staged.config.js ; is listed in .gitignore
Found & ignored ./package-lock.json ; is listed in .gitignore
Found & ignored ./package.json ; is listed in .gitignore
Found & ignored ./pnpm-lock.yaml ; is listed in .gitignore
Found & ignored ./postcss.config.js ; is listed in .gitignore
Found & ignored ./README.md ; is listed in .gitignore
Found & ignored ./STANDARD.md ; is listed in .gitignore
Found & ignored ./tsconfig.json ; is listed in .gitignore
Found & ignored ./vite.config.ts ; is listed in .gitignore
  ^

Error: Cannot find module 'D:\temp\menu-admin\lint-staged'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[master 2ef4569] docs: 📚 规范文档调整
```

#### Concise Description
执行  报错  上
#### Expected behavior
没有按期执行
#### Steps to reproduce
git  add  .   cz

**Comment by Zhengqbbb** [comment]
> Error: Cannot find module 'D:\temp\menu-admin\lint-staged'

`lint-staged` 的未找到模块错误

你可以试试仅用 `git commit -m "docs: 📚 规范文档调整"` 命令进行调试，
如果有问题可以提供最小化例子 或 查看一下其他issue 希望可以帮助到你
